#Create a Deployment by using the image pushed to Docker Hub
#Use containerPort 8081
#To create the deployment, get the values from ConfigMap and secret and follow the below instructions
#Use environment variable MYSQL_URL from ConfigMap, which is used in the SpringBoot application
#Use environment variables MYSQL_USERNAME for username and MYSQL_PASSWORD for password to access values from Secret
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      k8.stackroute: sb-deployment
  template:
    metadata:
      labels:
        k8.stackroute: sb-deployment
    spec:
      containers:
        - name: sb-k8-configmap-secret
          image: jaswanth1234/sb-userservice:1.0
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: sb-config
                  key: mysql_url
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: mysql_password
          ports:
            - containerPort: 8081
---
#Create the Service of type LoadBalancer and use the above created Deployment as selector
#Use port 8081
apiVersion: v1
kind: Service
metadata:
  name: sb-service
  labels:
    app: sb-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
      k8.stackroute: sb-deployment

